### PR TITLE
Remove unwanted dependency improve docs

### PR DESCRIPTION
**Pull request by jeffminsungkim**
#231

### CODE REVIEW

**Comment by bashleigh** [comment]
Do you need to update dotenv or is it the correct version already? I'm guessing it is?

**Comment by jeffminsungkim** [comment]
@bashleigh We're good to go :)

**Comment by jeffminsungkim** [comment]
@bashleigh Wait, I forgot to remove `@types/dotenv` from devDependencies.

**Comment by jeffminsungkim** [comment]
@bashleigh Now we're good to go :)

**Comment by bashleigh** [comment]
Thanks! :)

**Pull request merged**
