### PR TITLE
add ^8.0.0 version support to @nestjs/common peer dependency

### LINKED ISSUE #484: Support nestjs v8
**Issue type:**

- [ ] question
- [ ] bug report
- [X] feature request
- [ ] documentation issue

**nestjs-config version**
1.4.9

**@nestjs/common+core or other package versions**
 - @nestjs/common: 8.*
 - @nestjs/core: 8.*

#### Excepted behavior 
Add v8 as a supported peer dependency.

npm 8 doesn't allow installing nestjs-config when @nestjs/common is >7.

### PR DESCRIPTION
**Pull request by orgads**
Fixes #484.

### CODE REVIEW

**Review by bashleigh — APPROVED** [review]

**Comment by bashleigh** [comment]
Thanks!

**Comment by orgads** [comment]
Thank you. When is the next release planned?

**Comment by bashleigh** [comment]
I'll bump it now for you :)

**Comment by bashleigh** [comment]
published as 1.4.10

**Comment by orgads** [comment]
Thank you very much.

**Pull request merged**
