### PR TITLE
Fixed custom env file path section in the doc for better understanding

### PR DESCRIPTION
**Pull request by jeffminsungkim**
We should at least provide a small example to help people for a better understanding.

### CODE REVIEW

**Comment by jeffminsungkim** [comment]
@bashleigh We've been already discussed it on #127. Therefore, I didn't open another issue on this PR on purpose.

**Comment by bashleigh** [comment]
Hey! Thanks for the PR @jeffminsungkim. I like the idea! Could you make it a separate section aimed directly at using the different staging environment files please? :) Does that make sense? 

So underneath the section you edited, add in a new subtitle like `using different env files` and add your example there? :) 

Keeps things nice a separate because someone might have a different path like `/var/www/.env` instead of `/var/www/app/.env` or whatever. Or they could have different files OR they could have different file name for different stages and a custom path. Know what I mean?

**Comment by jeffminsungkim** [comment]
@bashleigh That makes sense. Sure, I'm happy to make one. 😀

**Comment by jeffminsungkim** [comment]
@bashleigh Please tell me if anything needs to be improved.

**Comment by jeffminsungkim** [comment]
@bashleigh Hey, I don't think I have permission to merge.😥

**Comment by bashleigh** [comment]
@jeffminsungkim no wonder nobody merges their PRs when I approve them :joy:

**Pull request merged**
